---
  - name: Install PHP Packages
    yum:
        name:
          - php
          - php-mysqlnd
        state: present

  - name: Restart apahe for PHP Integration
    service:
        name: httpd
        state: restarted

  - name: Create a PHP File for Testing PHP
    copy:
        dest: /var/www/html/file.php
        content: "<?php phpinfo?(); ?>"
        owner: apache
        group: apache
        mode:  0644



